Solution
tretikoff/SoftwareDesign pull request #1
Opened 2021-02-15 09:09 UTC by tretikoff

2021-02-17 13:01 UTC, tretikoff commented
Пока не работает запуск скрипта из gradle (gradle run), долго сидел, но не смог понять почему приходит бесконечный поток EOF в консоль

2021-02-18 15:49 UTC, FirstTimeInForever requested changes
Функциональность.
1. У вас не работает запуск внешних процессов.
2. Пайпы не всегда работают. Например `$cat README.md | wc`.
3. Кавычки. Сравните с тем, что происходит в баше.
```
$VAR=pwd
$$VAR
/tretikoff-SoftwareDesign
$VAR="pwd"
$$VAR
"pwd": command not found
$Feb 18, 2021 5:02:56 PM MainKt main
SEVERE: "pwd": command not found
$VAR='pwd'
$$VAR
'pwd': command not found
$Feb 18, 2021 5:03:25 PM MainKt main
SEVERE: 'pwd': command not found
```

Теперь про архитектуру. Почему у вас всё лежит в дефолтном пакете? На джаве вам явно должны были рассказывать про нейминг пакетов. Плюс из-за этого могут возникать всякие приколы с системами сборки/библиотеками/тестами т. к. не все умеют обрабатывать дефолтный пакет. 
У вас программа завязана на глобальный стейт в `main.kt` это следует исправить. Например, завести сущность `Shell` как я писал выше. Иначе будут потенциальные проблемы с многопоточностью, да и вообще, а что если захочется создать несколько инстансов вашего cli (например, если потребуется реализовать поддержку сабшеллов)? Кроме потоков такую сущность можно параметризировать, например, фабрикой для создания команд (паттерн абстрактная фабрика). В самом `main` стоит только обрабатывать аргументы и создавать из них инстанс шелла и вызывать у него метод, запускающий цикл ввода/исполнения команд.
В идеале, логика по парсингу команд должна быть в одном месте (например, в сущности `Parser`).  У вас же, часть разбора в `main`, а часть в `Word`.

Общие замечания:
* Старайтесь не оставлять функции на верхнем уровне. Старайтесь заворачивать их в неймспейсы (в `object`)
* Не пишите больших функций. Их сложно читать и поддерживать.
* Старайтесь больше использовать иммутабельные переменные и структуры данных (не стоит делать `MutableList` там, где можно обычный не мутабельный).
* Для запуска предлагайте не `gradle run`, а `./gradlew run` т. к. глобального градла может и не быть, а тот, который у вас в проекте всегда есть (если вы его запушили).
* При написании документации к классам и методам используйте `KDoc` и комментируйте `@param`/`@return`... . Это гораздо лучше читается ну и можно автоматом генерировать документацию ([`dokka`](https://github.com/Kotlin/dokka)).
* Используйте `detekt` для котлина. Есть плагин для идеи.

Поправьте функционал и архитектуру. Хоть в этом курсе архитектурные моменты являются более важными, всё-таки постарайтесь поправить замечания по коду.

2021-02-18 15:49 UTC, FirstTimeInForever commented on src/main/kotlin/CommandFactory.kt
> +    companion object {
`object CommandFactory`

2021-02-18 15:49 UTC, FirstTimeInForever commented on src/main/kotlin/exceptions/CommandNotFoundException.kt
> +    Exception("$cmd: command not found")
Обычно для своих исключений заводят отдельный базовый класс (например, `CliException`) и наследуются уже от него. Такой подход позволит ловить сразу все типы ваших исключений.

2021-02-18 15:49 UTC, FirstTimeInForever commented on src/main/kotlin/main.kt
> +    while (curr < pipeIndexes.size - 1) {
`for ((curr, prev) in pipeIndexes.zipWithNext())`

2021-02-18 15:49 UTC, FirstTimeInForever commented on src/main/kotlin/main.kt
> +var stdin = descriptors[0]
Не стоит заводить глобальный стейт. Почти всё содержимое `main.kt` следует собрать в одну (или несколько) сущностей. Например, сделать класс `Shell`, который будет параметризироваться потоками и другими вещами. Туда же стоит перенести логику input loop.

2021-02-18 15:49 UTC, FirstTimeInForever commented on src/test/kotlin/CatTest.kt
> +import org.junit.Test
Лучше использовать аннотации из `kotlin.test`, а сам `junit` использовать в качестве бэкенда.

2021-02-18 15:49 UTC, FirstTimeInForever commented on src/test/kotlin/BashTest.kt
> +    val fileContent = listOf("first line", "second line", "", "fourth line")
Лучше завести директорию с несколькими тестовыми файлами.

2021-02-18 15:49 UTC, FirstTimeInForever commented on src/test/kotlin/CatTest.kt
> +            assert(stdout.read() == line)
Используйте `assertEquals` т. к. при фейле он выдаст гораздо больше информации чем просто `assert`. Плюс идея имеет очень хорошую интеграцию c тестовыми фреймворками и, например, в случае фейла `assertEquals` покажет diff между ожидаемым и тем, что было на самом деле.

2021-02-18 15:49 UTC, FirstTimeInForever commented on src/test/kotlin/CatTest.kt
> +    fun catFileInput() {
В котлине можно очень удобно называть тестовые методы используя ``. Так, например, можно назвать этот кейс  ``` `file input` ```. Это сильно улучшает читаемость при запуске большого количества тестов.

2021-02-18 15:49 UTC, FirstTimeInForever commented on src/main/kotlin/CommandFactory.kt
> +            for (word in words) {
Вот этот кусок выглядит очень сложным. Я бы не стал бы его комментировать, если бы взгляд не зацепился за `fun findKey()`. Такие штуки лучше делать через комбинации `filter`/`map`/`any` для коллекций. Ну или хотя бы вынести `findKey` в отдельный метод. Всё таки мы пишем код не только для себя, но и для других разработчиков.

2021-02-18 15:51 UTC, FirstTimeInForever commented
> Пока не работает запуск строки CLI из gradle (gradle run), долго сидел, но не смог понять почему приходит бесконечный поток EOF в консоль

Добавьте в `build.gradle.kts`:
```
tasks.getByName<JavaExec>("run") {
    standardInput = System.`in`
}
```
и запускайте `./gradlew run --console=plain`.

2021-02-25 13:23 UTC, tretikoff commented
@FirstTimeInForever исправил все кроме двух моментов
- 3 из функциональности
- Не везде смог заменить структуры данных на иммутабельные

2021-02-27 18:30 UTC, FirstTimeInForever requested changes
Архитектурно всё окей (не считая минорных деталей). Мне кажется, вы забыли перенаправить ввод/вывод внешних команд потому что они ничего не выводят. Вам нужно поправить обработку ошибок - сейчас неизвестные команды роняют шелл. Плюс иногда неправильно сформированные команды не сообщают о синтаксических ошибках - `$cat README.md |`. В остальном всё хорошо.

Поправьте пожалуйста внешние процессы и обработку ошибок.

2021-02-27 18:30 UTC, FirstTimeInForever commented on build.gradle.kts
> +    mainClassName = "MainKt"
Вы забыли добавить префикс с пакетом: `mainClassName = "ru.tretikoff.MainKt"`. Без этого не работает `./gradlew run`.

2021-02-27 18:30 UTC, FirstTimeInForever commented on src/main/kotlin/ru/tretikoff/main.kt
> +var shell: Shell = Shell(descriptors)
Зачем делать инстанс шелла глобальным? Достаточно создавать его внутри `main`. В тестах его можно сделать полем в ` BashTest`.

2021-02-27 18:30 UTC, FirstTimeInForever commented on src/main/kotlin/ru/tretikoff/streams/Stream.kt
> +open class Stream {
Наверное этот класс должен быть абстрактным.

2021-03-01 17:11 UTC, tretikoff commented
@FirstTimeInForever done

2021-03-06 19:22 UTC, FirstTimeInForever approved these changes
У вас неправильно работает замена переменных и пайпы со внешними командами. В обоих случаях фиксы достаточно тривиальны (для того чтобы починить внешние команды достаточно перенести их создание в фабрику - я это в прошлый раз не заметил). 
Немного отличаются одинарные кавычки от баша:
```
$x='some'
$$x
Mar 06, 2021 9:54:52 PM ru.tretikoff.words.Word substituteVariables
INFO: replacing $x with 'some' in $x
Mar 06, 2021 9:54:52 PM ru.tretikoff.commands.ExternalCommand execute
INFO: Executing external command 'some' failed
Mar 06, 2021 9:54:52 PM ru.tretikoff.commands.ExternalCommand execute
INFO: 'some'
Mar 06, 2021 9:54:52 PM ru.tretikoff.Shell handleException
SEVERE: 'some': command not found
'some': command not found
```

С учётом grep: `6/7`

2021-03-06 19:22 UTC, FirstTimeInForever commented on src/main/kotlin/ru/tretikoff/words/Word.kt
> +            value = value.replace(regex, replacement)
```suggestion
            value = value.replaceRange(match.range, replacement)
```
Из-за этого у вас заменяется сразу всё, что попадает под регэсп, на значение первой переменной.

2021-03-06 19:22 UTC, FirstTimeInForever commented on src/main/kotlin/ru/tretikoff/Shell.kt
> +            }
```suggestion
            try {
                val pipeIndexes = extractPipes(words)
                if (pipeIndexes.isEmpty()) {
                    val c = CommandFactory.build(words, stdin, stdout, stderr)
                    c?.execute()
                } else {
                    executePipedStatements(words, pipeIndexes)
                }
            } catch (e: CliException) {
                handleException(e)
            }
```

2021-03-06 19:22 UTC, FirstTimeInForever commented on src/main/kotlin/ru/tretikoff/CommandFactory.kt
> +                else -> throw CommandNotFoundException(tokens[0])
```suggestion
                else -> ExternalCommand(ins, outs, errs, tokens.toMutableList(), tokens.first())
```

2021-03-20 22:07 UTC, FirstTimeInForever commented
CI сломался. Eсли вам будут делать PR, то лучше его починить :) В любом случае 👍 `7/7`.

2021-03-24 04:45 UTC, merged